### ISSUE TITLE
"TypeError: Cannot read property 'mode' of undefined" on fresh Quasar/Apollo project

### ISSUE THREAD

**Issue by SteveAtFenestra** [quasarframework/app-extension-apollo#58] opened 2020-07-04 17:48 UTC
I am unable to get a Quasar app running after installing this extension; it fails with the above error during compilation. I get the same error whether I try from a Windows 10 PowerShell prompt or an Amazon Cloud9 (Ubuntu) prompt, so I doubt that the environment has anything to do with the problem. The problem occurs whether the GraphQL server is running or not. The error message is so generic that I have no idea where to look to try to troubleshoot the problem. (One oddity is that the compilation step reports two errors, but only one error message is displayed.)

Steps:

1) Create a new Quasar app with `quasar create`:

```
? Project name (internal usage for dev) apollo-graphql-demo
? Project product name (must start with letter if building mobile apps) Apollo GraphQL Demo
? Project description Apollo GraphQL Demo
? Author ....
? Pick your favorite CSS preprocessor: (can be changed later) SCSS
? Pick a Quasar components & directives import strategy: (can be changed later) Auto import
? Check the features needed for your project: ESLint (recommended), Axios
? Pick an ESLint preset: Prettier
? Continue to install project dependencies after the project has been created? (recommended) NPM
```

If I try to start the app at this point with `quasar dev`, everything works fine.

2) Install the extension:

```
? GraphQL endpoint URI (You can skip it now and set it later) http://localhost:3500
```

If I try to run the app now, I get the aforementioned error:

```
 Dev mode.......... spa
 Pkg quasar........ v1.12.8
 Pkg @quasar/app... v2.0.1
 Debugging......... enabled

 Configured browser support (at least 84.46% of global marketshare):
 · Chrome for Android >= 81
 · Firefox for Android >= 68
 · Android >= 81
 · Chrome >= 73
 · Edge >= 79
 · Firefox >= 69
 · iOS >= 10.0-10.2
 · Opera >= 64
 · Safari >= 10.1

 App · Running "@quasar/apollo" Quasar App Extension...
 App · Reading quasar.conf.js
 App · Checking listening address availability (0.0.0.0:8080)...
 App · Extension(@quasar/apollo): Extending quasar.conf...
 App · Transpiling JS (Babel active)
 App · Extending SPA Webpack config
 App · Generating Webpack entry point
 App · Booting up...

 • Compiling:
 └── SPA ████████████████████ 100% done in 4519 ms



 ERROR  Failed to compile with 2 errors                                                                       1:22:11 PM


 error

Template execution failed: TypeError: Cannot read property 'mode' of undefined

 error
```

Windows version info:

```
PS ....\demo> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      18362  0
```

AWS Cloud9 environment info:

```
....:~/environment/demo (master) $ cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
....:~/environment/demo (master) $ uname -r
4.14.181-108.257.amzn1.x86_64
```

**Comment by stphdenis** [comment] 2020-07-07 11:51
It's due to `htmlWebpackPlugin.options` to be removed from the template for `Quasar V2`.

See #56 and #57.

**Comment by stphdenis** [comment] 2020-07-07 11:53
Duplicate of #56 and #57.

**Comment by stphdenis** [comment] 2020-07-08 13:33
Use @quasar/apollo@1.0.0-beta.6

**Closed** 2020-07-08 13:46 UTC
