### ISSUE TITLE
Remove ssrForceFetchDelay hack and introduce temporary disable network fetches

### ISSUE THREAD

**Issue by dmitry** [quasarframework/app-extension-apollo#34] opened 2020-02-15 20:39 UTC
Instead of `ssrForceFetchDelay` hack I really want to suggest you to include:

```javascript
    if (!process.env.SERVER) {
      // It is a hack to solve issues of ssrForceFetchDelay, see App.mounted to see where it's enabling back the network fetches
      apolloProvider.defaultClient.disableNetworkFetches = true
    }
```

before apolloProvider will be resolved in the boot.

Then somewhere in the App.vue in mounted must be included the following code:

```javascript
  mounted () {
    if (!process.env.SERVER) {
      this.$apolloProvider.defaultClient.disableNetworkFetches = false
    }
  }
```

That one will prevent from the issue when dehydration goes too late, and HTML code not connected to the Vue.

So this code should be removed at all:

https://github.com/quasarframework/app-extension-apollo/blob/ba720a1043223118ec46d98ef4f7ec783b1c1333/src/templates/src/quasar-app-extension-apollo/apollo-client-config.js#L51

More on this issue is you can read here: https://github.com/apollographql/apollo-client/issues/4814

**Comment by ejez** [comment] 2020-02-16 04:12
Thanks!

- The objective of this extension is to port the official install procedure of Vue Apollo into Quasar, so we should stick to instructions in https://apollo.vuejs.org/guide/ssr.html as much as possible, and instead open an issue in https://github.com/vuejs/vue-apollo/issues, or refer to an old similar one https://github.com/vuejs/vue-apollo/issues/194

- The extension should avoid modifying user files as much as possible, App.vue belongs to the app owner and should not be modified by the extension. (we did this only for index.template.html because it was stated in the official vue plugin instructions, and we also added a note about that in the readme file)

Now discussing the technical side of the issue, I don't see a reason to set `ssrForceFetchDelay` or (the method you suggested) at all, because the server will not send the response to the client until all the queries are resolved (use of [rendered](https://ssr.vuejs.org/guide/data.html#final-state-injection) hook), and when the client receives the response it will first fill in the cache with the query results before using it to instantiate the apollo client, the apollo client should then find the data in the cache and avoid fetching again (except if there is a bug in the apollo client instantiation logic, which then suggests moving the issue there)

@dmitry did you encounter the issue with updated versions and without setting `ssrForceFetchDelay`? if yes can you provide a reproduction procedure.

A side note, when using the `mounted()` hook, there is no need to check for `!process.env.SERVER`, as this hook gets called only in the client, https://ssr.vuejs.org/guide/universal.html#component-lifecycle-hooks

**Comment by dmitry** [comment] 2020-02-17 21:14
> A side note, when using the mounted() hook, there is no need to check for !process.env.SERVER, as this hook gets called only in the client

Thanks for noticing, really forgot about that, very nice point!

Other than that I will try when I got some free time to try new app-extension-apollo.

**Comment by ejez** [comment] 2020-02-19 06:35
@smolinari you can close this

**Closed** 2020-02-19 09:52 UTC
