### ISSUE TITLE
Composition API and Quasar v2 support 

### ISSUE THREAD

**Issue by hognevevle** [quasarframework/app-extension-apollo#51] opened 2020-06-22 21:19 UTC
The extension should probably support the Composition API of Vue Apollo, such as `useQuery`, `useMutation` etc. 

https://v4.apollo.vuejs.org/api/use-query.html 

I realize this is still only in alpha, so this issue is mostly for tracking.

**Comment by smolinari** [comment] 2020-06-29 17:15
Just FYI, but we'll need Quasar on Vue3, before we change this AE. So, we are a while off, before that happens. 

Scott

**Comment by stphdenis** [comment] 2020-07-08 11:49
In the meen time, you can add the package `@vue/composition-api@0.5.0` and modify `apollo-clmient-hooks.js` like this :
```js
import { provide } from '@vue/composition-api'
import { DefaultApolloClient } from '@vue/apollo-composable'
...
export function apolloClientAfterCreate ({
  apolloClient,
  app,
  //router, store, ssrContext, urlPath, redirect
}) {
  app.setup = () => {
    provide(DefaultApolloClient, apolloClient)
  }
  // if needed you can modify here the created apollo client
}
```

For the moment, versions newer than `0.5.0` of the package `@vue/composition-api` are not compatible with the last current package `@vue/apollo-composable` (4.0.0-alpha.8)

You could'd also need the function `toRef` from newer versions of `@vue/composition-api` :
```ts
import { isRef } from "@vue/composition-api";
import { createRef, Ref } from "@vue/composition-api/dist/reactivity";

export function toRef<T extends object, K extends keyof T>(object: T, key: K): Ref<T[K]> {
  const v = object[key];
  if (isRef<T[K]>(v)) return v;

  return createRef({
    get: () => object[key],
    set: (v) => (object[key] = v),
  });
}
```

**Comment by philon123** [comment] 2020-07-18 10:41
Hi, thanks for this really nice info! I tried to follow your instructions to backport "toRef" support by creating a file `src/toRefCompatibility.ts` with your code, but getting following error:
```This dependency was not found:
@vue/composition-api/dist/reactivity in ./src/toRefCompatibility.ts
```

VS Code does find that folder and doesn't show me an error. Just the command line compiler complains.. Any idea what's going on?

**Comment by maspendig** [comment] 2021-01-22 10:05
Thanks @stphdenis for the integration hint. Btw.: The is no compatibility problem since version 4.0.0-alpha.10 of @vue/apollo-composable as mentioned [here](https://github.com/vuejs/vue-apollo/issues/1009#issuecomment-670309087).

**Comment by smolinari** [comment] 2021-01-25 08:42
@ejez - (and all) I'm going to be attacking this issue and creating version 2 in the next week or two, since Vue 3 is out and Quasar v2 is around the corner. Would you (anyone) be interested in some (more) collaboration?

Scott

**Comment by oliversteiner** [comment] 2021-02-09 13:56
Hello Scott
I'd love to help you out with this request. I am actually porting one of my Apps from Vue 2 / REST to Quasar Vue 3 / GraphQL. I have no Deadlines, so i can testing your progress in a Real World App, or even help you to rewrite the Code for Composition API.

**Comment by smolinari** [comment] 2021-02-10 04:28
@oliversteiner - Thanks for the offer. Are you on Discord? Ping me please Scott (EN-DE)#0052

Scott

**Comment by oliversteiner** [comment] 2021-02-10 07:54
Hey Scott i have made a Discord Account ( OliverSteiner#5240 ) Let's get in contact.

**Comment by smolinari** [comment] 2021-02-10 13:33
@oliversteiner - Can you enter into the Quasar Discord server? Otherwise, I can't DM you or you me. 😁 

https://discord.gg/8MbthT2n

Scott

**Comment by smolinari** [comment] 2021-02-16 07:17
@oliversteiner - Did you miss the above? 😁 

I've started work on v2 of the extension. I've got the composition API working, it's just not where I'd like it to be, as it seems, you can't cleanly hook into the root component's `setup` function. See here: https://github.com/smolinari/app-extension-apollo/discussions/3

Scott

**Comment by ejez** [comment] 2021-03-06 15:58
Hi Scott,
Can you test with this: `quasar ext add @ejez/apollo`
Installation/usage instructions: https://gitlab.com/ejez/app-extension-apollo/-/blob/main/README.md
Use a typescript app.

You'll get a warning: `"export 'onServerPrefetch' was not found in 'vue-demi'`,  you can ignore it while waiting for https://github.com/vuejs/vue-next/pull/3070 or suppress it with:
`node_modules/@vue/apollo-composable/dist/useQuery.js`
```diff
...
import { ref, isRef, computed, watch, 
// @ts-expect-error
-onServerPrefetch, getCurrentInstance, onBeforeUnmount, nextTick, } from 'vue-demi';
+getCurrentInstance, onBeforeUnmount, nextTick, } from 'vue-demi';
...
import { trackQuery } from './util/loadingTracking';
+const onServerPrefetch = null;
```

**Comment by ejez** [comment] 2021-03-06 16:08
For now, only vue apollo composition api is supported, also no ssr support...  waiting for upstream projects...

**Comment by smolinari** [comment] 2021-03-06 16:10
Yeah. I was that far too. :grin: https://github.com/smolinari/app-extension-apollo/tree/v2-work/src

I'm sure your work is a step up from mine though. I'll test it tomorrow. 

Scott

**Comment by smolinari** [comment] 2021-03-07 08:31
@ejez - Can we chat on Discord?

Scott

**Comment by jvmonjo** [comment] 2021-03-09 14:48
> Can you test with this: `quasar ext add @ejez/apollo`

Your implementation compiles without issues but when I try to make a query with useQuery, I get this error:

`Uncaught (in promise) Error: Apollo client with id default not found. Use provideApolloClient() if you are outside of a component setup.`

**Comment by smolinari** [comment] 2021-03-09 15:53
@jvmonjo - Have to ask the stupid question, but did you follow the instructions in README.md? 

Scott

**Comment by jvmonjo** [comment] 2021-03-09 16:08
> @jvmonjo - Have to ask the stupid question, but did you follow the instructions in README.md? 
> 
> Scott

Sure I have. But anyway my issue is in reference to @ejez/apollo implementation

**Comment by smolinari** [comment] 2021-03-09 16:24
> > @jvmonjo - Have to ask the stupid question, but did you follow the instructions in README.md?
> > Scott
> 
> Sure I have. But anyway my issue is in reference to @ejez/apollo implementation

😁 - Yes, I am referring to the instructions in Ejez's repo.

Scott

**Comment by jvmonjo** [comment] 2021-03-09 16:31
Fair enough, 😁 No I haven't. I thought they were the same. I will and I'll
post the results.

El dt., 9 de març 2021, 17:24, Scott <notifications@github.com> va escriure:

**Comment by ejez** [comment] 2021-03-16 16:19
Thanks for the feedback @jvmonjo

**Comment by maggie0002** [comment] 2021-04-14 03:02
> Fair enough, 😁 No, I haven't. I thought they were the same. I will and I'll post the results. **Edit**: After making the change suggested in the readme I confirm `@ejez/apollo` works. Thanks.

What was it in the readme that resolved it for you? The only thing I didn't do was use the defineComponent method, I stuck with separate files for the gql:

```
import gql from 'graphql-tag'

export const GET_LEVELS = gql`
  query levels{
      levels(sort: "published_at:asc") {
          id
          level
      }
  }
`
```

Then call them from the file using it:

```
import { GET_LEVELS } from '../gql/level/queries'

const { result: fetchedLevels, loading: fetchLevelsLoading, refetch: fetchLevels } = useQuery(GET_LEVELS)
```

Didn't want to change everything to align it all in one file because it will get long and messy pretty quick.

**Comment by smolinari** [comment] 2021-04-14 04:09
@maggie0002 - which readme? :)

Scott

**Comment by maggie0002** [comment] 2021-04-14 04:56
> Hi Scott,
> Can you test with this: `quasar ext add @ejez/apollo`
> Installation/usage instructions: https://gitlab.com/ejez/app-extension-apollo/-/blob/main/README.md
> Use a typescript app.
> 
> You'll get a warning: `"export 'onServerPrefetch' was not found in 'vue-demi'`, you can ignore it while waiting for [vuejs/vue-next#3070](https://github.com/vuejs/vue-next/pull/3070) or suppress it with:
> `node_modules/@vue/apollo-composable/dist/useQuery.js`
> 
> ```diff
> ...
> import { ref, isRef, computed, watch, 
> // @ts-expect-error
> -onServerPrefetch, getCurrentInstance, onBeforeUnmount, nextTick, } from 'vue-demi';
> +getCurrentInstance, onBeforeUnmount, nextTick, } from 'vue-demi';
> ...
> import { trackQuery } from './util/loadingTracking';
> +const onServerPrefetch = null;
> ```

This one.

**Comment by ejez** [comment] 2021-04-14 05:26
Did you **provide** the Apollo client in App.vue?
https://gitlab.com/ejez/app-extension-apollo/-/blob/main/README.md#appvue

**Comment by maggie0002** [comment] 2021-04-14 05:30
> Did you **provide** the Apollo client to the rest of your components from App.vue?
> https://gitlab.com/ejez/app-extension-apollo/-/blob/main/README.md#appvue

Yep: https://github.com/LearnersBlock/library/blob/q2/src/App.vue

**Comment by ejez** [comment] 2021-04-14 05:38
Your project is Quasar v1, the above was for v2, follow this instead: https://github.com/quasarframework/app-extension-apollo/issues/93#issuecomment-815459060

**Comment by ejez** [comment] 2021-04-14 05:42
sorry was looking at the wrong branch, one sec ...

**Comment by ejez** [comment] 2021-04-14 06:02
Can you try to reproduce in a new clean project, so we can isolate the issue in an easier way... thx

**Comment by smolinari** [comment] 2021-04-14 06:24
@ejez - Thanks for jumping in. 

Would you mind PRing your version into the repo? How about if we add a "next" branch and I'll remove the "v2-next" branch? Or just PR into that one? Not sure what would be easiest for you.

Scott

**Comment by ejez** [comment] 2021-04-14 06:34
Hi Scott, will try to do it later today, either "next" or "v2" will do. (not both together)

**Comment by ejez** [comment] 2021-04-14 06:44
I prefer "v2", what do you think

**Comment by maggie0002** [comment] 2021-04-14 06:54
> Can you try to reproduce in a new clean project, so we can isolate the issue in an easier way... thx

Seems like the issue is stemming from here, in App.vue:

```
    const { onError } = useQuery(GET_RESOURCES)

    onError(() => {
      setTimeout(() => {
        apiIsUp.value = false
      }, 1000)
    })
```

It is executed right after `provide(DefaultApolloClient, apolloClient)`. It was happy enough in the old version, but not so happy here. Not a major issue, will write something else to do the same thing that it will get along with, but noting here in case it indicates anything more to you guys.

Thanks for taking a look, and putting the time in to developing the extension.

**Comment by smolinari** [comment] 2021-04-14 13:35
@ejez  - Yeah, that is fine. v2 it is. 😁 Just have to figure out how to get the branch added, as I don't have full perms for the repo. 

Scott

**Comment by smolinari** [comment] 2021-04-14 19:36
FYI, the next version (v2) is now in the v2 branch. Thanks goes to @ejez for his awesome work!

Scott

**Comment by maggie0002** [comment] 2021-05-31 21:58
> onServer

onServerPrefetch should now be resolved in the latest beta: https://github.com/vuejs/vue-apollo/issues/1102#issuecomment-836317916

**Comment by maggie0002** [comment] 2021-05-31 21:59
> Hi Scott,
> Can you test with this: `quasar ext add @ejez/apollo`
> Installation/usage instructions: https://gitlab.com/ejez/app-extension-apollo/-/blob/main/README.md
> Use a typescript app.
> 
> You'll get a warning: `"export 'onServerPrefetch' was not found in 'vue-demi'`, you can ignore it while waiting for [vuejs/vue-next#3070](https://github.com/vuejs/vue-next/pull/3070) or suppress it with:
> `node_modules/@vue/apollo-composable/dist/useQuery.js`
> 
> ```diff
> ...
> import { ref, isRef, computed, watch, 
> // @ts-expect-error
> -onServerPrefetch, getCurrentInstance, onBeforeUnmount, nextTick, } from 'vue-demi';
> +getCurrentInstance, onBeforeUnmount, nextTick, } from 'vue-demi';
> ...
> import { trackQuery } from './util/loadingTracking';
> +const onServerPrefetch = null;
> ```

onServerPrefetch should now be resolved in the latest beta: https://github.com/vuejs/vue-apollo/issues/1102#issuecomment-836317916

**Comment by Am3ra** [comment] 2021-08-02 16:41
Any update on getting apollo to quasar V2?

**Comment by smolinari** [comment] 2021-08-03 04:33
> Any update on getting apollo to quasar V2?

> [FYI, the next version (v2) is now in the v2 branch. ](https://github.com/quasarframework/app-extension-apollo/issues/51#issuecomment-819781214)

https://github.com/quasarframework/app-extension-apollo/tree/v2

Scott

**Comment by hipertracker** [comment] 2022-01-06 06:39
v2 does not work. `vue-router.esm-bundler.js?f6c4:3295 Error: Apollo client with id default not found. Use provideApolloClient() if you are outside of a component setup.`

**Comment by smolinari** [comment] 2022-01-06 10:22
@hipertracker - It certainly works. You have a problem with your code or setup. Are you trying to call the client outside of a component? If yes, you have the answer in front of you.

Scott

**Comment by hipertracker** [comment] 2022-01-06 12:46
@smolinari no, it does not. To reproduce the bug I have created a new Quasar project and added a simple component. https://github.com/hipertracker/b8-frontend
After running `quasar dev` command I can see a blank page and the following errors in the Chrome Developers tool:

```
vue-router.esm-bundler.js?f6c4:3295 Error: Apollo client with id default not found. Use provideApolloClient() if you are outside of a component setup.
    at resolveClient (webpack-internal:///./node_modules/@vue/apollo-composable/dist/index.esm.js:60)
    at start (webpack-internal:///./node_modules/@vue/apollo-composable/dist/index.esm.js:289)
    at immediate (webpack-internal:///./node_modules/@vue/apollo-composable/dist/index.esm.js:505)
    at callWithErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6829)
    at callWithAsyncErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6838)
    at job (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:7243)
    at doWatch (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:7288)
    at watch (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:7129)
    at useQueryImpl (webpack-internal:///./node_modules/@vue/apollo-composable/dist/index.esm.js:503)
    at useQuery (webpack-internal:///./node_modules/@vue/apollo-composable/dist/index.esm.js:240)
triggerError @ vue-router.esm-bundler.js?f6c4:3295
4index.esm.js?0df5:48 Uncaught (in promise) Error: Apollo client with id default not found. Use provideApolloClient() if you are outside of a component setup.
    at resolveClient (webpack-internal:///./node_modules/@vue/apollo-composable/dist/index.esm.js:60)
    at start (webpack-internal:///./node_modules/@vue/apollo-composable/dist/index.esm.js:289)
    at immediate (webpack-internal:///./node_modules/@vue/apollo-composable/dist/index.esm.js:505)
    at callWithErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6829)
    at callWithAsyncErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6838)
    at job (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:7243)
    at doWatch (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:7288)
    at watch (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:7129)
    at useQueryImpl (webpack-internal:///./node_modules/@vue/apollo-composable/dist/index.esm.js:503)
    at useQuery (webpack-internal:///./node_modules/@vue/apollo-composable/dist/index.esm.js:240)
    ```

**Comment by hipertracker** [comment] 2022-01-06 12:50
I can see also some TS warnings but they are not the main problem 
![image](https://user-images.githubusercontent.com/649/148385529-8dfd2f42-a6fb-4181-8c24-10eff1a1cfc2.png)

**Comment by smolinari** [comment] 2022-01-07 14:26
@hipertracker - Not sure what to tell you. Everything works fine for me. You might want to try removing `node_modules`, and any lock files and reinstall dependencies. 

Scott

**Comment by hipertracker** [comment] 2022-01-08 20:27
@smolinari  did you try this from scratch?

```
git clone https://github.com/hipertracker/b8-frontend.git
cd b8-frontend
yarn
quasar dev
```

Have you not any Typescript warnings in the terminal, really? 

Has your Chrome browser not any errors in the Developer Tools?

What Node are you using? I use 16.13.1

**Comment by smolinari** [comment] 2022-01-09 05:15
@hipertracker - By "works fine for me" I mean, it works fine in my project. You naturally have to set up the extension i.e. set up the apollo client and use your "options" properly to get everything to work. 

Scott

**Comment by hipertracker** [comment] 2022-01-10 00:44
@smolinari  "it works in my project" sounds like nothing to me. I have created a sample project to reproduce the bug.  Do you want to help or only to say f**k off?

**Comment by smolinari** [comment] 2022-01-10 06:08
@hipertracker - I did download your reproduction repo and ran it before I made my last comment above. Your repo is not set up to do anything. Do some set up (use the options object and get the client options you need going) and if necessary, change `any` to `unknown`. That should get you a step further. This repo makes the assumption you know what you are doing with Apollo Client and only gets you the initial scaffolding to start setting up Apollo for your Quasar project. 

Scott

**Comment by smolinari** [comment] 2022-01-16 07:33
@hipertracker - Someone else just had the same problem as you were having and I believe it's a simple error of not adding the apollo boot file to `quasar.conf.js`. 

I'm closing this issue too, as the OP is resolved in the end. 

Scott

**Closed by smolinari** 2022-01-16 07:33 UTC
Labels: enhancement
