### ISSUE TITLE
ApolloClient not accessible from route and boot

### ISSUE THREAD

**Issue by stphdenis** [quasarframework/app-extension-apollo#14] opened 2019-08-18 14:47 UTC
By using **Apollo**, even with **Vue**, the use of the **apollo-cache** is now often preferred on **Vuex**.

We have at least two ways to make it available from the router:
1 - replace **Vuex** by **ApolloClient**,
2 - add **ApolloClient** as a second store to be passed to the router and boot files.

The first choice asks to choose between **Vuex** and **ApolloClient**.
The second choice requires a small modification of the **Quasar** kernel.

**Comment by dmitry** [comment] 2019-09-05 13:12
On which stage would you replace Vuex by ApolloClient? By design it's possible to replace store inside the `store/index.js`, place there initialization of the apollo client. This kind of change is very limited to the SSR mode, as inside the `store` you are not able to access to the `ssrContext`, which is serious limitation for me. That's the only one point I found how you could replace vuex store by apollo client. It's not possible to change it on the next steps, for example inside the boot files.
Lets discuss of the possible solutions to the 1 way.

I've implemented second solution without any modifications in the latest quasar with boot file. If you have any problems with this implementation - just let me know. It also works with SSR mode as well.

**Comment by smolinari** [comment] 2020-02-15 02:11
Closing as old. 

Scott

**Closed by smolinari** 2020-02-15 02:11 UTC

**Comment by dmitry** [comment] 2020-02-15 20:29
@smolinari hopefully that will be fixed as well in the newer versions.

**Comment by smolinari** [comment] 2020-02-16 06:54
Try it out and see. The way it works now and IMHO, you should use Apollo for global state management. You'll also need to take the paradigm of the Flux pattern with Vuex and change it a bit to components that need only the data they need and changing only the data they need to change, making data a forth clear concern within components. So, nothing more about wanting some call to get data via the router. That shouldn't be necessary any more. But, let's see. We can always change and improve as we move forward. 😃  

Scott

**Comment by thedelk** [comment] 2020-04-17 02:05
In my current project we're using both **Vuex** (with the [Vuex-Pathify](https://davestewart.github.io/vuex-pathify/) plugin, which has been a huge game-changer) and **ApolloClient** and I had a similar question.

In case anyone comes across this and needs to know how to access the **ApolloClient** from an external file (e.g. another `.js` file), here's what I did after asking around in the [Quasar Discord](https://chat.quasar.dev).

[(Here's the direct link to the answer I got in Discord).](https://discordapp.com/channels/415874313728688138/614917106491981837/687917218134097934)

---

In your `apollo-client-hooks.js` file (in `src/plugins/quasar-app-extension-apollo`), you can export the `apolloClient` object from the `apolloClientAfterCreate` function.

Here's what mine looks like:

```javascript
// src/plugins/quasar-app-extension-apollo/apollo-client-hooks.js

let apollo = {}

export function apolloClientBeforeCreate () {}

export function apolloClientAfterCreate ({ apolloClient }) {
  apollo = apolloClient
}

export { apollo }
```

Now the client is accessible from wherever it needs to be called.

For example, I make GraphQL mutations in some of the actions in my **Vuex** store.

```javascript
// store/some-store-module.js

import { apollo } from '@/quasar-app-extension-apollo/apollo-client-hooks'

const actions = {
  onCreate ({ dispatch }, { myMutation, myVariables }) {
    apollo.mutate({
      mutation:  myMutation,
      variables: myVariables
    })
  }
}
```

Hopefully this helps anyone else who needs it!

**Comment by M1chaelTran** [comment] 2020-05-18 14:47
Has anyone else able to use multiple clients with this client hooks?
https://apollo.vuejs.org/guide/multiple-clients.html

I managed to set up the apollo-provider-hook to return multiple clients and that works great.
However, I'm not able to set up multiple clients with the apollo-client-hooks.
